/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FeedbackEntry = IDL.Record({
  'id' : IDL.Int,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const MeditationRecord = IDL.Record({
  'duration' : IDL.Nat,
  'moodBefore' : IDL.Nat,
  'date' : IDL.Text,
  'memo' : IDL.Text,
  'moodAfter' : IDL.Nat,
});
export const MeditationRecordWithId = IDL.Record({
  'id' : IDL.Int,
  'record' : MeditationRecord,
});
export const TreeState = IDL.Record({
  'personality' : IDL.Text,
  'stayHere' : IDL.Bool,
  'cycleCompleteShown' : IDL.Bool,
  'cycleIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Int],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Int], [], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getAllRecordsWithIds' : IDL.Func(
      [],
      [IDL.Vec(MeditationRecordWithId)],
      ['query'],
    ),
  'getTotalMinutes' : IDL.Func([], [IDL.Nat], ['query']),
  'getTreeState' : IDL.Func([], [TreeState], ['query']),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'recordVisit' : IDL.Func([], [IDL.Nat], []),
  'setTreeState' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool], [], []),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateRecord' : IDL.Func([IDL.Int, IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FeedbackEntry = IDL.Record({
    'id' : IDL.Int,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const MeditationRecord = IDL.Record({
    'duration' : IDL.Nat,
    'moodBefore' : IDL.Nat,
    'date' : IDL.Text,
    'memo' : IDL.Text,
    'moodAfter' : IDL.Nat,
  });
  const MeditationRecordWithId = IDL.Record({
    'id' : IDL.Int,
    'record' : MeditationRecord,
  });
  const TreeState = IDL.Record({
    'personality' : IDL.Text,
    'stayHere' : IDL.Bool,
    'cycleCompleteShown' : IDL.Bool,
    'cycleIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Int],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Int], [], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getAllRecordsWithIds' : IDL.Func(
        [],
        [IDL.Vec(MeditationRecordWithId)],
        ['query'],
      ),
    'getTotalMinutes' : IDL.Func([], [IDL.Nat], ['query']),
    'getTreeState' : IDL.Func([], [TreeState], ['query']),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'recordVisit' : IDL.Func([], [IDL.Nat], []),
    'setTreeState' : IDL.Func([IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool], [], []),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateRecord' : IDL.Func([IDL.Int, IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };