/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MeditationRecord = IDL.Record({
  'duration' : IDL.Nat,
  'moodBefore' : IDL.Nat,
  'date' : IDL.Text,
  'memo' : IDL.Text,
  'moodAfter' : IDL.Nat,
});
export const MeditationRecordWithId = IDL.Record({
  'id' : IDL.Int,
  'record' : MeditationRecord,
});

export const idlService = IDL.Service({
  'addRecord' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Int],
      [],
    ),
  'deleteRecord' : IDL.Func([IDL.Int], [], []),
  'getAllRecordsWithIds' : IDL.Func(
      [],
      [IDL.Vec(MeditationRecordWithId)],
      ['query'],
    ),
  'getTotalMinutes' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MeditationRecord = IDL.Record({
    'duration' : IDL.Nat,
    'moodBefore' : IDL.Nat,
    'date' : IDL.Text,
    'memo' : IDL.Text,
    'moodAfter' : IDL.Nat,
  });
  const MeditationRecordWithId = IDL.Record({
    'id' : IDL.Int,
    'record' : MeditationRecord,
  });
  
  return IDL.Service({
    'addRecord' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Int],
        [],
      ),
    'deleteRecord' : IDL.Func([IDL.Int], [], []),
    'getAllRecordsWithIds' : IDL.Func(
        [],
        [IDL.Vec(MeditationRecordWithId)],
        ['query'],
      ),
    'getTotalMinutes' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };